name: Deploy

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_ENDPOINT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY_OF_NETCUP }}
          script: |
            sudo docker login https://ghcr.io -u zkdev --password ${{ secrets.ZKDEV_PACKAGE_ACTIONS }}
            sudo docker stop run-it-down-crawler
            sudo docker rm run-it-down-crawler
            sudo docker pull ghcr.io/run-it-down/crawler:latest
            sudo docker run -dit --name run-it-down-crawler --net host ghcr.io/run-it-down/crawler:latest
